# Generated by Django 4.0.6 on 2023-03-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('NO POVERTY', 'NO POVERTY'), ('ZERO HUNGER', 'ZERO HUNGER'), ('GOOD HEALTH & WELL-BEING', 'GOOD HEALTH & WELL-BEING'), ('QUALITY EDUCATION', 'QUALITY EDUCATION'), ('GENDER EQUALITY', 'GENDER EQUALITY'), ('CLEAN WATER & SANITATION', 'CLEAN WATER & SANITATION'), ('AFFORDABLE & CLEAN ENERGY', 'AFFORDABLE & CLEAN ENERGY'), ('DECENT WORK & ECONOMIC GROWTH', 'DECENT WORK & ECONOMIC GROWTH'), ('INDUSTRY, INNOVATION & INFRASTRUCTURE', 'INDUSTRY, INNOVATION & INFRASTRUCTURE'), ('REDUCE INEQUALITIES', 'REDUCE INEQUALITIES'), ('SUSTAINABLE CITIES & COMMUNITIES', 'SUSTAINABLE CITIES & COMMUNITIES'), ('RESPONSIBLE CONSUMPTION', 'RESPONSIBLE CONSUMPTION'), ('CLIMATE ACTION', 'CLIMATE ACTION'), ('LIFE BELOW WATER', 'LIFE BELOW WATER'), ('LIFE ON LAND', 'LIFE ON LAND'), ('PEACE, JUSTICE & STRONG INSTITUTIONS', 'PEACE, JUSTICE & STRONG INSTITUTIONS'), ('PARTNERSHIPS FOR THE GOALS', 'PARTNERSHIPS FOR THE GOALS')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('project_type', models.CharField(choices=[('Service Learning', 'Service Learning'), ('Community-Based Research', 'Community-Based Research'), ('Organised Outreach', 'Organised Outreach')], max_length=80)),
                ('completion_code', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7, null=True)),
                ('campus', models.CharField(choices=[('APK', 'APK'), ('APB', 'APB'), ('SWC', 'SWC'), ('DFC', 'DFC')], max_length=3)),
                ('cellphone', models.CharField(max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('access_number', models.CharField(max_length=9)),
                ('hours_completed', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SVC.volunteer')),
                ('occupation', models.CharField(max_length=50, null=True)),
            ],
            bases=('SVC.volunteer',),
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=120)),
                ('vcs_needed', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('expected_duration', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SVC.project')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SVC.volunteer')),
                ('faculty', models.CharField(choices=[('Faculty of Science', 'Faculty of Science'), ('Faculty of Education', 'Faculty of Eduction'), ('Faculty of Humanities', 'Faculty of Humanities'), ('Faculty of Law', 'Faculty of Law'), ('Faculty of Health Sciences', 'Faculty of Health Sciences'), ('Faculty of Arts, Design and Architecture', 'Faculty of Arts, Design and Architecture'), ('College of Business and Economics', 'College of Business and Economics'), ('Faculty of Engineering and The Built Enviroment', 'Faculty of Engineering and The Built Enviroment')], max_length=100)),
                ('course', models.CharField(max_length=80)),
                ('recruiting_id', models.CharField(blank=True, max_length=64, null=True)),
                ('goal', models.CharField(choices=[('NO POVERTY', 'NO POVERTY'), ('ZERO HUNGER', 'ZERO HUNGER'), ('GOOD HEALTH & WELL-BEING', 'GOOD HEALTH & WELL-BEING'), ('QUALITY EDUCATION', 'QUALITY EDUCATION'), ('GENDER EQUALITY', 'GENDER EQUALITY'), ('CLEAN WATER & SANITATION', 'CLEAN WATER & SANITATION'), ('AFFORDABLE & CLEAN ENERGY', 'AFFORDABLE & CLEAN ENERGY'), ('DECENT WORK & ECONOMIC GROWTH', 'DECENT WORK & ECONOMIC GROWTH'), ('INDUSTRY, INNOVATION & INFRASTRUCTURE', 'INDUSTRY, INNOVATION & INFRASTRUCTURE'), ('REDUCE INEQUALITIES', 'REDUCE INEQUALITIES'), ('SUSTAINABLE CITIES & COMMUNITIES', 'SUSTAINABLE CITIES & COMMUNITIES'), ('RESPONSIBLE CONSUMPTION', 'RESPONSIBLE CONSUMPTION'), ('CLIMATE ACTION', 'CLIMATE ACTION'), ('LIFE BELOW WATER', 'LIFE BELOW WATER'), ('LIFE ON LAND', 'LIFE ON LAND'), ('PEACE, JUSTICE & STRONG INSTITUTIONS', 'PEACE, JUSTICE & STRONG INSTITUTIONS'), ('PARTNERSHIPS FOR THE GOALS', 'PARTNERSHIPS FOR THE GOALS')], max_length=50)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SVC.student')),
            ],
            bases=('SVC.volunteer',),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SVC.occurrence')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SVC.staff')),
                ('vc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SVC.student')),
            ],
        ),
    ]
