# Generated by Django 4.0.6 on 2023-02-23 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours_completed', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SD_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours_completed', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('APK', 'Kingsway'), ('APB', 'Bunting'), ('SWC', 'Soweto'), ('DFC', 'Doornfontein')], max_length=7, null=True)),
                ('campus', models.CharField(choices=[('APK', 'Kingsway'), ('APB', 'Bunting'), ('SWC', 'Soweto'), ('DFC', 'Doornfontein')], max_length=3)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('login_number', models.IntegerField()),
                ('hours_completed', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SVC.volunteer')),
                ('occupation', models.CharField(max_length=50, null=True)),
            ],
            bases=('SVC.volunteer',),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('date', models.DateTimeField()),
                ('expected_duration', models.IntegerField()),
                ('VCs_needed', models.IntegerField()),
                ('project_type', models.CharField(choices=[('SL', 'Service Learning'), ('CBR', 'Community-Based Research'), ('OO', 'Organised Outreach')], max_length=80)),
                ('venue', models.CharField(max_length=120)),
                ('completion_code', models.CharField(max_length=60, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SVC.sd_goal')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SVC.volunteer')),
                ('num_recruits', models.IntegerField()),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SVC.faculty')),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SVC.student')),
            ],
            bases=('SVC.volunteer',),
        ),
    ]
