# Generated by Django 3.2.4 on 2023-03-13 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 13, 11, 2, 26, 302757)),
        ),
    ]
