# Generated by Django 3.2.4 on 2023-02-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
