# Generated by Django 3.2.4 on 2023-03-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVC', '0002_alter_volunteer_hours_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=120)),
                ('vcs_needed', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('expected_duration', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expected_duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vcs_needed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='venue',
        ),
    ]
