# Generated by Django 3.2.4 on 2023-02-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SVC', '0002_alter_volunteer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SVC.student'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hours_completed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
