# Generated by Django 3.2.4 on 2023-03-12 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SVC', '0003_auto_20230312_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SVC.project'),
        ),
    ]
