# Generated by Django 3.2.4 on 2023-03-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVC', '0005_alter_participant_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='date',
        ),
    ]
