# Generated by Django 3.2.4 on 2023-03-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVC', '0006_remove_participant_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='project',
            new_name='occurrence',
        ),
    ]
